# Muffin Vs Cupcake Prediction Using Recipe Dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

## Reading our dataset using pandas

In [2]:
recipe = pd.read_csv("recipes_muffins_cupcakes.csv")
recipe

       Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0

## Changing our categorical Values "Muffin and Cupcake" into binary values

In [3]:
label = np.where(recipe["Type"] == "Muffin", 0, 1)

In [4]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Assigning dependent varibales to y and Independet variables to X

In [29]:
X = recipe[["Flour", "Milk", "Sugar", "Butter", "Egg", "Baking Powder", "Vanilla", "Salt"]]
y = label

In [30]:
X

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0      55    28      3       7    5              2        0     0
1      47    24     12       6    9              1        0     0
2      47    23     18       6    4              1        0     0
3      45    11     17      17    8              1        0     0
4      50    25     12       6    5              2        1     0
5      55    27      3       7    5              2        1     0
6      54    27      7       5    5              2        0     0
7      47    26     10      10    4              1        0     0
8      50    17     17       8    6              1        0     0
9      50    17     17      11    4              1        0     0
10     39     0     26      19   14              1        1     0
11     42    21     16      10    8              3        0     0
12     34    17     20      20    5              2        1     0
13     39    13     17      19   10              1        1     0
14     38    15     23      15    8              0        1     0
15     42    18     25       9    5              1        0     0
16     36    14     21      14   11              2        1     0
17     38    15     31       8    6              1        1     0
18     36    16     24      12    9              1        1     0
19     34    17     23      11   13              0        1     0

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Splitting training and testing

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Fitting our Logistic Regression Algorithm inside our training dataset

In [34]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train, y_train)
regressor

LogisticRegression()